---
title: Istjerivači duhova
hero_image: images/ghostbusters.png
description: Napravi igru​ hvatanja duhova!
original_url: https://www.codeclubprojects.org/en-GB/scratch/ghostbusters
theme: green
listed: true
copyedit: true
ingredient: false
duration: 2
curriculum: builder, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: games
technologies: scratch
site_areas: codeclub, scratch
steps:
  - 
    title: Uvod
  - 
    title: Trebat ćeš
  - 
    title: Animacija duha
  - 
    title: Nasumični duhovi
  - 
    title: Hvatanje duhova
  - 
    title: Dodavanje rezultata
  - 
    title: Dodavanje mjerača vremena
  - 
    title: 'Challenge: više objekata'

