---
title: ഗോസ്റ്റ്ബസ്റ്ററുകൾ
hero_image: ചിത്രങ്ങൾ / ghostbusters.png
description: പ്രേതങ്ങളെ പിടികൂടുന്നതിൽ ഒരു കളി സൃഷ്ടിക്കുക!
original_url: https://www.codeclubprojects.org/en-GB/scratch/ghostbusters
theme: പച്ച നിറം
listed: true
copyedit: true
ingredient: false
duration: 2
curriculum: builder, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: ഗെയിമുകൾ
technologies: സ്ക്രാച്ച്
site_areas: codeclub, scratch
steps:
  - 
    title: ആമുഖം
  - 
    title: What you'll need
  - 
    title: Animating a ghost
  - 
    title: Random ghosts
  - 
    title: Catching ghosts
  - 
    title: Adding a score
  - 
    title: Adding a timer
  - 
    title: 'വെല്ലുവിളി: കൂടുതൽ വസ്തുക്കൾ'

