---
title: ഗോസ്റ്റ്ബസ്റ്ററുകൾ
hero_image: ചിത്രങ്ങൾ / ghostbusters.png
description: പ്രേതങ്ങളെ പിടികൂടുന്നതിൽ ഒരു കളി സൃഷ്ടിക്കുക!
original_url: https://www.codeclubprojects.org/en-GB/scratch/ghostbusters
theme: പച്ച നിറം
listed: true
copyedit: true
ingredient: false
duration: 2
curriculum: ബിൽഡർ, ഡിസൈൻ -0, പ്രോഗ്രാമിങ് -1, phys-comp-0, ഉൽപാദന-0, കമ്മ്യൂണിറ്റി -0
interests: ഗെയിമുകൾ
technologies: സ്ക്രാച്ച്
site_areas: കോഡ്ക്ലബ്, സ്ക്രാച്ച്
steps:
  - 
    title: ആമുഖം
  - 
    title: നിങ്ങൾക്ക് എന്ത് വേണം
  - 
    title: ഒരു പ്രേതം
  - 
    title: ക്രമരഹിതമായ പ്രേതം
  - 
    title: പ്രേതം
  - 
    title: ഒരു സ്കോർ ചേർക്കുന്നു
  - 
    title: ഒരു ടൈമർ ചേർക്കുന്നു
  - 
    title: 'വെല്ലുവിളി: കൂടുതൽ വസ്തുക്കൾ'

