---
title: Ghostbusters
hero_image: images / ghostbusters.png
description: Naredite igro o lovu duhov!
original_url: https://www.codeclubprojects.org/en-GB/scratch/ghostbusters
theme: zelena
listed: true
copyedit: true
ingredient: false
duration: 2
curriculum: builder, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: igre
technologies: praska
site_areas: codeclub, scratch
steps:
  - 
    title: Uvod
  - 
    title: What you'll need
  - 
    title: Animating a ghost
  - 
    title: Random ghosts
  - 
    title: Catching ghosts
  - 
    title: Adding a score
  - 
    title: Adding a timer
  - 
    title: 'Izziv: več predmetov'

