---
title: Ghostbusters
hero_image: imej / ghostbusters.png
description: Buat permainan tentang menangkap hantu!
original_url: https://www.codeclubprojects.org/en-GB/scratch/ghostbusters
theme: hijau
listed: true
copyedit: true
ingredient: false
duration: 2
curriculum: builder, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: permainan
technologies: awal
site_areas: codeclub, scratch
steps:
  - 
    title: Pengenalan
  - 
    title: What you'll need
  - 
    title: Animating a ghost
  - 
    title: Random ghosts
  - 
    title: Catching ghosts
  - 
    title: Adding a score
  - 
    title: Adding a timer
  - 
    title: 'Cabaran: lebih banyak objek'

