---
title: Ghostbusters
hero_image: images/ghostbusters.png
description: Crea un gioco di acchiappa-fantasmi!
original_url: https://www.codeclubprojects.org/en-GB/scratch/ghostbusters
theme: green
listed: true
copyedit: true
ingredient: false
duration: 2
curriculum: builder, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: games
technologies: scratch
site_areas: codeclub, scratch
steps:
  - 
    title: Introduzione
  - 
    title: Di cosa avrai bisogno
  - 
    title: Animare un fantasma
  - 
    title: Fantasmi a caso
  - 
    title: Acchiappare i fantasmi
  - 
    title: Aggiungere un punteggio
  - 
    title: Aggiungere un timer
  - 
    title: 'Sfida: Altri oggetti'

