---
title: Hayalet Avcıları
hero_image: images / ghostbusters.png
description: Hayaletleri yakalama oyunu yapın!
original_url: https://www.codeclubprojects.org/en-GB/scratch/ghostbusters
theme: yeşil
listed: true
copyedit: true
ingredient: false
duration: 2
curriculum: builder, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: oyunlar
technologies: çizik
site_areas: codeclub, scratch
steps:
  - 
    title: Giriş
  - 
    title: What you'll need
  - 
    title: Animating a ghost
  - 
    title: Random ghosts
  - 
    title: Catching ghosts
  - 
    title: Adding a score
  - 
    title: Adding a timer
  - 
    title: 'Meydan Okuma: Daha fazla nesne'

